# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print('Numpy Version: {}'.format(np.__version__))
print()
print('Numpy Config: ')
np.show_config()


Numpy Version: 1.16.2

Numpy Config: 
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vec = np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
num_bites = vec.size * vec.itemsize
print('{} bytes'.format(num_bites))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(0,9)
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
vec = [1,2,0,0,4,0]
print(np.nonzero(vec))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
matrix = np.random.random((3,3,3))
print(matrix)

[[[0.05967553 0.98469367 0.5833631 ]
  [0.82764226 0.45544742 0.24028681]
  [0.13922804 0.72701191 0.19346001]]

 [[0.36010148 0.55741668 0.45528846]
  [0.05226226 0.794348   0.29984931]
  [0.32411544 0.79905197 0.12166407]]

 [[0.7247034  0.97256359 0.62316958]
  [0.40189091 0.88445898 0.47395202]
  [0.86214059 0.83437909 0.332646  ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
matrix = np.random.random((10,10))
min_val = matrix.min()
max_val = matrix.max()
print(matrix)
print('Minimum Value: {}'.format(min_val))
print('Maximum Value: {}'.format(max_val))

[[0.42120638 0.9333434  0.87409519 0.23907041 0.23934396 0.30649262
  0.12118595 0.82704324 0.56815716 0.20483945]
 [0.73013454 0.04563284 0.63566386 0.78058428 0.20839476 0.07702208
  0.26359294 0.8299997  0.26656597 0.28617929]
 [0.08271164 0.78508883 0.16895803 0.32937895 0.02478868 0.02871791
  0.33746156 0.08720479 0.86701459 0.5500906 ]
 [0.95674844 0.14971528 0.70020499 0.87953484 0.60079555 0.17492756
  0.14783074 0.51880499 0.70891632 0.67421756]
 [0.51666548 0.5186784  0.035798   0.87187628 0.88656417 0.04684005
  0.76902347 0.26626635 0.64499775 0.24913719]
 [0.70570499 0.32961803 0.2787625  0.09321008 0.05908619 0.73568569
  0.51355737 0.0990816  0.22694682 0.80590438]
 [0.01751287 0.7875847  0.99393025 0.42708812 0.89902443 0.23961009
  0.5623476  0.46769897 0.00787434 0.54178467]
 [0.96001822 0.17453358 0.57686603 0.49130423 0.02181659 0.48046092
  0.63305586 0.6037973  0.83052526 0.79966996]
 [0.55424155 0.62038216 0.20367503 0.26110813 0.01860503 0.18180596
  0.47188627

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
vec = np.random.random(30)
mean = vec.mean()
print(vec)
print(mean)

[0.75727099 0.45218145 0.16020919 0.48268903 0.86352581 0.50958676
 0.09444231 0.73476024 0.07835291 0.45400818 0.71622087 0.84314451
 0.38058178 0.35146798 0.42479685 0.63223554 0.22265627 0.84208753
 0.37922711 0.19512831 0.64084707 0.2407516  0.22388653 0.944665
 0.58788719 0.80004007 0.4706124  0.64198973 0.92381635 0.08990506]
0.504632487513184


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
np.pad(array, 1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
vec = np.arange(1,5)
np.diag(vec, -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
array = np.ones((8,8))
array[::2, 1::2] = 0
array[1::2, ::2] = 0
print(array)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
vec = np.arange(6*7*8)
vec.reshape((6,7,8))
#np.info(np.unravel_index)
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
#np.info(np.tile)
vec = np.array([[0,1],[1,0]])
check = np.tile(vec, (4,4))
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
mat = np.random.random((5,5))
mat = (mat - np.mean(mat)) / np.std(mat)
print(mat)

[[-1.42405995  1.20287232  0.30764083 -1.80705963 -1.27209539]
 [ 1.10338077  0.29467538 -0.86731296 -0.67787372 -0.32319657]
 [-0.35904328  1.13921727  0.13235305  0.16735346 -0.03581475]
 [-1.01529025 -0.42214378  0.15979734  1.50700274  0.10749405]
 [ 0.81775892  1.84778373  0.0453      1.21089878 -1.8396384 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
np.dtype([('r', np.ubyte, 1),
          ('g', np.ubyte, 1),
          ('b', np.ubyte, 1),
          ('a', np.ubyte, 1)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.random.random((5,3))
b = np.random.random((3,2))
prod = np.dot(a,b)
print(np.shape(prod))
print(prod)

(5, 2)
[[0.58428032 0.43827766]
 [0.26672751 0.15930104]
 [0.94493347 0.54566992]
 [0.92982706 0.63725253]
 [0.56913158 0.33560405]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [61]:
a = np.arange(1,11)
a[(3<a) & (a<8)] *= -1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z = np.arange(11)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [36]:
a = np.random.uniform(high=1,low=-1,size=10)
print(a)
a = np.copysign(np.ceil(np.abs(a)),a)
print(a)

[-0.68265463 -0.26442856  0.87904389 -0.28952697  0.58383027  0.66858959
 -0.13866843  0.57264519  0.18579101  0.31675744]
[-1. -1.  1. -1.  1.  1. -1.  1.  1.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [41]:
a = np.arange(10)+3
b = np.arange(10)
print(np.intersect1d(a,b))

[3 4 5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [42]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [43]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

2019-04-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [60]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [63]:
a = np.ones(3)*2
b = np.ones(3)*3
np.add(a,b,out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a,b, out=a)
print(a)

[-5. -5. -5.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [68]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 8. 6. 2. 2. 8. 1. 7. 1. 6.]
[9. 8. 6. 2. 2. 8. 1. 7. 1. 6.]
[9. 8. 6. 2. 2. 8. 1. 7. 1. 6.]
[9 8 6 2 2 8 1 7 1 6]
[9. 8. 6. 2. 2. 8. 1. 7. 1. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [71]:
a = np.arange(5)
np.tile(a, (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [84]:
def generator():
    for x in range(10):
        yield x
a = np.fromiter(generator(), dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [91]:
a = np.random.random(10)
b = np.linspace(0,1,endpoint=False, num=11)[1:]
print(b)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [94]:
a = np.random.random(10)
a.sort()
print(a)

[0.13380178 0.3326261  0.36639947 0.46240005 0.66543466 0.68580982
 0.7180244  0.88146001 0.94708398 0.95005319]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [95]:
a = np.arange(11)
print(np.add.reduce(a))

55


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [127]:
a = np.random.randint(0,2,3)
b = np.random.randint(0,2,3)

equal = np.allclose(a,b)
print(equal)

equal = np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [128]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [133]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
polar = np.stack((R,T), axis=1)
print(polar)

[[0.22092131 0.39719779]
 [0.00523495 0.94768281]
 [0.01640047 0.45424083]
 [0.10175956 0.1389037 ]
 [0.68908734 0.89461856]
 [0.68026062 0.1108701 ]
 [0.42861474 0.06744456]
 [0.71907561 0.98073536]
 [0.14954817 0.10507241]
 [0.11990403 0.26263453]]
[[0.45450227 1.06320569]
 [0.94769727 1.56527244]
 [0.45453681 1.53470677]
 [0.17218957 0.93853057]
 [1.12924033 0.91445549]
 [0.68923631 0.16156128]
 [0.43388866 0.15607498]
 [1.21610509 0.93813391]
 [0.18276999 0.61246821]
 [0.28871071 1.14251436]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [137]:
vec = np.random.random(10)
print(vec)
vec[np.argmax(vec)] = 0
print(vec)

[0.55552829 0.77070463 0.26697027 0.07378689 0.15019793 0.15655313
 0.29080321 0.0659861  0.5812952  0.86647781]
[0.55552829 0.77070463 0.26697027 0.07378689 0.15019793 0.15655313
 0.29080321 0.0659861  0.5812952  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [138]:
np.info(np.meshgrid)

 meshgrid(*xi, **kwargs)

Return coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of
N-D scalar/vector fields over N-D grids, given
one-dimensional coordinate arrays x1, x2,..., xn.

.. versionchanged:: 1.9
   1-D and 0-D cases are allowed.

Parameters
----------
x1, x2,..., xn : array_like
    1-D arrays representing the coordinates of a grid.
indexing : {'xy', 'ij'}, optional
    Cartesian ('xy', default) or matrix ('ij') indexing of output.
    See Notes for more details.

    .. versionadded:: 1.7.0
sparse : bool, optional
    If True a sparse grid is returned in order to conserve memory.
    Default is False.

    .. versionadded:: 1.7.0
copy : bool, optional
    If False, a view into the original arrays are returned in order to
    conserve memory.  Default is True.  Please note that
    ``sparse=False, copy=False`` will likely return non-contiguous
    arrays.  Furthermore, more than one element of a broadcast array
    may refe

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)